language: ruby
sudo: false
dist: xenial

notifications:
  email: false

rvm: 2.5.3

addons:
  apt:
    packages:
      - libgtk-3-dev
      - libmysqlclient-dev

stages:
  - test

jobs:
  include:
    - stage: test
      before_install:
        - ./scripts/setup.sh
      script:
        - bundle exec rake
